### PR TITLE
Refactor many things

### PR DESCRIPTION
**Pull request by Septrum101**
Now integrated lego for apply certs and auto update.

Deleted the outdated golist.json. Added helper functions for handling requests in helper.go. Added version.go for handling the version command in the CLI. Added renew_test.go and lego_test.go for unit tests. Added accounts_storage.go, certs_storage.go and setup.go for handling certificate renewal. These changes are made to improve the code architecture and maintainability.

### CODE REVIEW

**Comment by Septrum101** [comment]
If you accpet this PR, the Client will be push in few days.

**Comment by julydate** [comment]
Nice PR. Thank you for your contribution!

**Comment by julydate** [comment]
> Now integrated lego for apply certs and auto update.
> 
> Deleted the outdated golist.json. Added helper functions for handling requests in helper.go. Added version.go for handling the version command in the CLI. Added renew_test.go and lego_test.go for unit tests. Added accounts_storage.go, certs_storage.go and setup.go for handling certificate renewal. These changes are made to improve the code architecture and maintainability.

Wait, I notice that you have changed a lot of codes and added some functions, but I don't have the energy to continue to develop these codes and the new features of this project, so I suggest you fork to your repositories and implement it as a new project, so as not to be affected by my lack of expertise.

**Comment by Septrum101** [comment]
Ok, I got it.

**Pull request merged**
